### ISSUE TITLE
aplt_testplan throws intermittent twisted:Unhandled Error

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/ap-loadtester#56]
running aplt_testplan w/ api_loadtest, basic scenarios on OSX

~~~
INFO:twisted:Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x00000001076058c0>
INFO:twisted:Handling websocket data:  {u'status': 200, u'channelID': u'022e5015-0994-49f5-8143-6e88876cce46', u'messageType': u'register', u'pushEndpoint': u'https://updates.push.services.mozilla.com/wpush/v1/gAAAAABXkQwgidYSCDQGTGrieuy8RIpTSS0xtmCvDGN97zMoiizRX88x_cv74yBdGEQCbMVPhUM3-WJ5BnPCvBTGrqUj8ClpxQmYuqRaNn-9500JvSoeQnW-Gmw7T1OSmxlRVkSoAVIr'}
INFO:twisted:Running command:  TimerStart(name='update.latency')
INFO:twisted:Running command:  SendNotification(endpoint_url=u'https://updates.push.services.mozilla.com/wpush/v1/gAAAAABXkQwgidYSCDQGTGrieuy8RIpTSS0xtmCvDGN97zMoiizRX88x_cv74yBdGEQCbMVPhUM3-WJ5BnPCvBTGrqUj8ClpxQmYuqRaNn-9500JvSoeQnW-Gmw7T1OSmxlRVkSoAVIr', data=None, ttl=60)
INFO:twisted:Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x00000001062f84a0>
INFO:twisted:Handling websocket data:  {u'status': 200, u'channelID': u'e5b1225b-2c5f-41de-818e-155651b6d507', u'messageType': u'register', u'pushEndpoint': u'https://updates.push.services.mozilla.com/wpush/v1/gAAAAABXkQwgseDUMiD45fyfTKx8yZKXcKnoBB-4gvc4n903Lam0P1s5vsUZH0kjoylvDMscW4tmC2clV1VzyYrUAGpLr7pbVQx0hTzdVBK4erZWk7g9ZI9upoNeJd1MqfJwcfIA9pkM'}
INFO:twisted:Running command:  TimerStart(name='update.latency')
INFO:twisted:Running command:  SendNotification(endpoint_url=u'https://updates.push.services.mozilla.com/wpush/v1/gAAAAABXkQwgseDUMiD45fyfTKx8yZKXcKnoBB-4gvc4n903Lam0P1s5vsUZH0kjoylvDMscW4tmC2clV1VzyYrUAGpLr7pbVQx0hTzdVBK4erZWk7g9ZI9upoNeJd1MqfJwcfIA9pkM', data='\xe1$\x17\x1b$\x84[\x06\xcc\x85\xc7C\x96%7\xdf\xc4\x15\xce\xb1dr::f\xf4\x0e\xe0"\x83\x90\xa7\xeds]\xd1\x06Hh1\r\x0e\xa8\xcf\xeb\xda\xe2\x94D\xb2\x0b2v\xdf{U\x02\xf9\xadC\x198%I!\x9e\xa6\xa9V\x87\x9b\xc8\xf7(\xb6\xa0\xcf\x7fF_#\xe1\xe8\xc2\xf5\x83\xa0\xdfj\x11\x1f\xab\x86\xf3\x0b\x96\\d\xfe\x8aYu\xc0\xb9:\xd6\x030 \xf4\x9b\xf0\xde\x19O\xc4\xbf\xb8\xf5\x95.\x85z\x9a\x02nO\x0c\x8cX\xfb\x9du\x00\xc9\xea\xb2\xb6\x1dV\xc9\xd3\xf1\xe0s\xec\xd9\x18\xf9,\x84V\x01\x16N\xaecB\x1e/\xa1\xd0!6\xc8\xe1\xc9\xa2\xbc\x19R\xb8\x9fH\xc5\x19b%\xe8\xf5[\x19\x16)H{\x10\xe0\xa5\xa9\x1a\xa6\xe1\x8d\x93~0@8\x9b\x11$F\r\x0e\xe2\xf8\x0e6\x0e\x1f\xe8<\x97O\x10\xf9T\xab\xdb\x945\xceD\xb09]JR\xee\xab\x13\xa4\x01\x17r\xfc#\xc7\xd4\xa5\x17\x95PIR\xf1>\x01\x9fCcH\xc8\x80\x9b\xdd5\xc0\xed\x9d\x07\x87R\xee\xa4{\xeel\xdc\x8a\xbf\x02\xf0\xe0\x15\xe7\x89\x00-\xc5\xc7\xd6\xa5\xd7\x07\x9d\x04\x8f\xaa\xf8+lRj\x96\xe0\xa8\xb2:#d\xf6\x81\xaam\xcf\x91\x01\xd7\x93\xa4KhGc\xb8|\xad\xb9\x11\xd4\xce\xb5_\x05Q\xe8\xcfb#\xb2*\xd3\x069\xba\x13\xf1\xe8\x91u\x14\x1c\xb8B~2\xc1-\xa5[:#\x86\xcea\x85\x0b\xa2\xd9@/\xd4\xcf>1\xc5$\xb6Y}\xe9*\xf0"\xd2\xc060\xff\x9e)\xe7]\xe6\xaa-\xb4[\xbe@I\x99\x86\xf23\x08&\x8c\x8dF\xe9a--E\xc5_\xf9\xad\xf0B\xbe\xf5>\x8d\xd15\xd1\xc8\xe4>\xaa\xa5:[u\xac|\xb2\xce\x9eXw\xden\x9b_\xce\xc4\xbc\xc6\xa7o\xe6m\xd2)\xfb\x92+4\xc0\x9b\x0f\x02\x08\x1bHM\xac7\x80\xca\x9e\x8b\x8d\xd3Br\xeeG\xa1d\xb2F3\xf9S\x91\nK|\xa1\xc6\x8f\xf1\xb7\x8a\x01\xc6\r/\x14k@\xbc\x16G\xa8\xf6Q\xab\x8bh]\x8c\x8d\xab\x08\xef\xf0J<\x98p\x94\x1em\xbcT\x82\x85\x9cj_\x98\xfc\x87\x82\x10\xf4\xa1T\xd3\xedb~\x81\x7f\x86\xb04~\'\x1eT{\xa4 E\n\xb7~<\x18\xd9r\x00dkV\xf8K*\x8dwMfrbQV\x05\x05\xf0n\x9e\x9cK\xac\xf1s \xa4B\x1d\x9aV\xf6\xd1fc\xb2\xecL\xd8\x12[\xb9$\xf6r\xf3\x06\x04\x91\x04_y)\xcb\x10\xc4\xf7\x08x\xa0\xd2",\xc6~\x17C\x07\xc7`\x0c\xb3\x14\x1cg\x96F\x08bekGw\x97\xc1\xed\xb6\x87\xe3\xd5\xac\x16^\x80\x9fNA\xf6\x9f=\x7f\xba\xa7\xc5\x860\xe0\x05\xac\xcb\xe2\xaf\x1c%\xd1\x1en\x95\xc8\x14g\xe45\xf8\xfaU\x06\x84\x7f\x948\x7f|\xd9@\xbc\xa2\x16E/\xcc\xc8\xb8\xdf\x97\xd4\x02H\x01\xba\xac*\xf7+\x94\xef\xe0\xa6]\x01\xd3\xfa\x85\xd5<\xc5\x8fY4\x14)\x14\x10c\xea\xd0\x9d\xe8\xcb\xd7\xb8\x1ap\xd5D*\xd8g\x03\xbd\x7f\xf4\xd7\xa6\xd6\xd6\xf1\xba\x1ac\x08w\x1b;Q\x96\xbf\xf6\xc17\x17\xd4\xf8\xc5\x87\xa1XRD\xc8\xc9\x1ed\x844\x91\xc8\xec|\xa1c\r\tyP\xe8\x08\x04&\x17\x07\x8ax\x06\xbb\x99\xf6\xa0\xa9\n\x05\x19\x9ag\xc3\x88\x14\xde\x16\x1e\x05H\xaa!W\xc7\xb0|\xb5\x05\xdc\xcd\x94t\xa6\x1a\x9dO\xf53\x15QK&\x9b\xfck\x0e^E\xb0\x9d$\x87\xd5\x08\xbcv\xb3\xbb\x10\x83\xfc1\xf07e\xe9\x85!\xfe\xb08}`|\r\x18\x8d\r\x18\xc5\x9ce\x83\xae\x9a\xdbE\xdel\x86`\xdd\xc2\xbb!\x7f5\x02lP\'\xfa\xd9~\x97\x9f$?S\xf2\xbd-\xa0\x93\x82\xd7\x17\xc6/\xb7\xc4\xa9\x1b\xbe\xf7\xec\xbe}\x85\x93\xc5\xa4\xee\x85\xca\xba^\xecYH\x8d\x9d\x9c\xe5\xab\xd2V\xf6jN-\x7f=\xf9p.\xd7\xdfdqY\x95\xe5\x9f\x81\x02\xcb\xc57\xd5\xbe1\xf8IS\x1f\x93\xca8\xe2\x06\x13uf{\xee\x7f\x03\xa8\t#\x8e\xa8\x0f\x0b\x02P\x06m\xde\xf4M\xf8\xe7\x90\xe3\xb1\xf5\xe2\xb3~*\x9f,\x0e\t\x9eg\x91\xfb\x8c\x1bl8R\xb8f E(mh\xc1\x03\x7f\x8a\x10\xa0\xd5\xc3\r\x01c\x18`R\x1cP9\x8a\xe7gd4~\xdf)=\x9d\x02\x93\xf9\xf4\xf6L\xda\x99>\x82\xa6\xe8&p\x83\xa1\x17uuY"\x91\x12\x9b\'\xf8\x853X\x9b\xafG\xcc\x03|\xac\xe2\xc7\xff/\x16\x81\xbc;\x03\xae;\x9d\x1b\xf8ws\xf4I\x84]\x00og\x10\tuCi\xd0\'g\x9f\x0e\x9a#D6S\x9e\xff\x92\x9a\x0c\xb1\xc6\x93 CZ\xbc?\x9eN\x00\xb6\xb0\xc3\x06$\xeajvM\x08\xc6MG\xdc\x99\x02\x82\xdcRs\xca\x0fE,f\xeb\xca>\x81{\x11\xd1C\x1d\xa9\xf4\x91\xc7\xd7\x1b\xd6\xa6\x80\x9aP\x85d\xd7]\xe6>\x13\x92\x9c\x8bi\x04\xf9\x98\xdb\x01\xe1\x08#\x08\xffQ%\xe4\x8cp(z\xd6\xf8d\xf6\xcf \xd2\xaa\x05xa\x83\xbeR\xc2\xa7\xe8k>\xf7\xbes\x8e\xedlx\xfb~\x93\xd6\xfaY\xb3\x9a"\xf2\xf0o\xc2k\xf2\x9b\xd5\x86\x1f\xe9\xaac.\x18\xa8\xcfB\xdf/GD\xf9Y8\xc2\x03\t\xb9\x00\xdb\xdb\x0b\x88\x1d4\x83 \xfe\x9ad\xa5\xa2\xce\x83\x10=\xe1\x00\xb8\x1f\xc8\xea\xfb:\x7f\xdaO2M\xf7\x1d\xbe\x16rx\xd2%j!%\xe0IM$;[\x1d)}\xe0V\xcd\\\xde\x1f\x7f\xb8\x9aS)\x1d\x03\x05W\xe3`\x08^\x82\xd1;\xd7\xd6\x19\xef\xe9\xb1\xdb\x87\x9d\xcfj\xf9\x13\xda ,\x1e\xd9/f\xb4\xf9\xf7x\x1b\xe6hk\xb1\xbb#\x8b\xbfk\x02@av\x9a\xac\x90\x94\xd2\xaa\x8d\x93\xaf\x12\x9c\x8ci\x9a&Z\x1f\x06\x92\xfe\x17\xe9M\x10\x96a>\x02\xcf\x9d\x8f}I\x00\x1a\xc3\xbe\xf47S\xaa\xc4\x12\xadEl\x8bg\xbb\xa8\xacP\xa4\xd3}\x99\xe7?\x8cIKb\xf8\xec\xe7G|\xe2Y?\xfe{\xa18\x86\x06\xd9\xe2r\xbb\xc7q(\x83\x8a\xd8=+\xe2\xbc\xf0 \xe0)\xa27\xe1\xc6\xe4\xb0\xc8\xef}=\xcb\x1fd\x93\xb4$\x7f\x91\x15\xc4\xa9\xedS->e\'\x0e\\76BHL_A\xd0y\xf0\xe5Y\xf5\xad\\\xd7\xfd\xd5\xe1\xfa\xa0\xd7\x1b\xba\xf0\x1a_C\xb7F\x8670\x98\x85\xde\xbaI\x9c\x05\x04\xccF<+kS\x85u^A\xbe\xa8\x1bF\x11\xa9\xd8C\xcds\xf9\x07\tc\x88,\x82\x02"\xbdf\xe5r\xa1\xdf\xba\x07\x9f\x80\x845\xac\x04\x89x:\xe7\xd0\x04\xbd\xb2\xedq\xa7&\xf7\x8f\x88\x92\xbfF\xf2\xda\xc9\x0b\xe8*\xb2\xb7\xd9\x009J\xd5\xa3\xdc\x97g\xc8\xe8Ct\xdfp\x84\xfe\xf1\x1d\xff\xf1}W\xae \x06\x99\x9d\xa1\xac\xf7%m9\xac\xdf\xb2\'x\xbc\xa9\x96\x02\xc4\xf9&\xa2\xe3\xfe0<\\*\x99\x03\xd3\x07~\xa1{<\xb35\xc4\xf3k\xcd\xa7\xf2\x89\x9b9\xecH\xd7\x80\x8f:\x94\x96;(#\x0c\x03\x8d\xc5Pe>\t\x0e\x16\xc3\x8e\xe1\x9cq>\x08\xb4\xda,\xe6s\x0f%#\x15\x8c\tX\x0cKl\x10\xb4s\x03\xd3\x1bN6K!w\xd8\xca^\xc7>\xa1vD\x14\x0b\x893K\x17\xcdbi\xa2\tP\xfe\x11\xed%\x99\xff\x04#\x80B\xd0\xcd\xa2\xbd\x973\xbf%\xa2\x04Y\xd4\xa9d\xacV\xd6-\xa0j\xd2\xfb\xb5\xdf\xd9\xe9\xa4\xaf\x91u\xa3\xe6\x13M\xebm\xdc\xcbYC\x932^\x89\x18c_\xa2\xceLRO\x02\x0c\x0f\xd2\x9b\xc8.\x9a\xd8kf7\xf0\xe0\xa4#c\x83UtE\xb0\xfeG1]\xc0\xe5(\x8a\xd1\xcf\xe5\xe2\x84Dt\xf1\x89\xf89\x17m\xc9\x97(K\x82l\xbd\xee9\xba\xfc\xa3_\\vB\x01\xd7\xa4\xb3_\xc9Pa\x19\x94\x90\xe4\xd6-\x1f\x0ci\x8d\xa0n\x10\x9f\xb1$\xe6\xae?\xca\x7f\xaf\x08q\xf6D\xbb\xc5\x82\x90Z\xc9>\x9c\x81\x85s,\x97\x80w[\xc4\xaa\x7fh\x8c\x1e\xcf\xa5\x9e\xa8\xc1v\xaf\xaeI7\xa9\x05c\xa6j\xb3G\x16\xc7\xa0)\x1c]\xac\x0b\xcd\x9f B+\xcda\x19F\xe4\xc0vR@c\xc7\xf8\x07\xe4\x0f:|&\xc4\xd8\x03\xd9\x97\xd5\x13\x17\x8f\xb68\xff\xefD\'K\x03\x0f\xa1\n\xc6\xcf\x923Z\xc8M(a\x01_\x1a\xc4\xf8\x1f\xd0\xf0k\xef\xf8\x18\xf7`}\x92\x95R\xea0n\x8d\xf9G\x15\x8dQ\xa1-\xe6+\\Zd5\x8b\xd2\xac\xde\xb6\xc8$"\xa6\x15\xd1\x9f\x05\x1e^\x19qx\xaf%\xfb\xd6\x11\xc7\x84\xe0\'K\n\xe8:u\xc6\x91t?G2\x1d\xfe@\xdf\xe2\xa5O\xa2p\xe3\xa7\xc2\x9a\xc1\x0e\x04b\xb7#\xb9\xff\xae7\x8d\x90)\xe4k\xa2\x9e"\xdb\xfa\x15K\xa2\xc6\xf4\x8f\xd4&\x95fj\x9bM\xc7KY\x86x@\xeb9\xaf\xe3\xb8M\xdaAb\xa9\xac\xdd\xb4\xd0\xd3.\r\xcbBT\xa7\xa3\xb9!\x96(+\xacNQ\xbc\xa0$\x03\xe8&\xe438\xfa\xba\xac\xe2\xc5\xbc?\xe0\x16#E\xdc\xfa\x1e\x7fJ,n\xa0\\\xf6\xb8\r\xb0Z~.\xfc\xdd\x87\x02\xc5d1\xd8\x92\x83\xf3\x0c\xb9\tx\xc1V(,\x91UT\x87\xccl\xb4\x02\x94>w\xee\xb3P\xabE\xbf\x0c\\\xa6\x1d\xdb\xaa8\x1fB\xce\x92\x1e\x19d\x1d\xa1\x1b\xb8\xc2g\x00E\x7fD=p\xdf\xe9F^\xcb\x8f\xec\x04\xbd\x99,`\xb0\xb3\x8b&\x9f\x9eu\xa5;\xd9h\x91\xd0A\x013C>b\xc2\xe34\x11\x08k\xe90\t\xd2|2\xcb\t\x88\xd7\xabd\xeb\x98\x95\xe1A\x11U\xd18@]6\xf9\xbc\xb4\xac\xdd\xc5"]\xd74\xb7\xcc\xbc\xe3\xa3\xad\x1a\x86,_&$v\xd7C\xf7\xa0=b\xb2\xc9\xd3f3\xdc\xc2Pc\x10z\xd8\xd7\xf2l\xc3\xb0\xa3\xe4\xd1\xe1m0\xbe\xbd\x1a;\x88\x0eHzo{Y\xf0\xa5!\x88\xa2T\x8d\x93\x11\xd3\xd2\x96\x8f\x19Z\x8c\xd9\xe02Y\xd7\xa3\xac\xe2\xa7Y\x9bv\xb4\xd8H\xf0i~\xea8\xddx\xe6\xab7\xe2\xc2\xe7\xd3\xac\x85\xb0\x13I\x08\xdf\xd2\xa76\xcc~-\xd8\x02(\xe1\xfc\x91+(\xfe\xfd4\xd6\xc2\xb0\xf0\x06\xd7\x1bd\xf1g\x84\xa9\x81\xf7\x1c9\xb0\xcf\xbc\xf3\xf1\xfa~n\xb5\x88D>\xbc\xff\xc4\xd3+\xa9;"\xd3\x9dGV6"$\x9c3\xac\xb4\xf5]4zylU\xb5\xa5>\xacv%Dt\xcap\xe7\xf0\x12\xc0V+\xfa\xed\x99T[,\xea\x99Q\x96\xca\']o\xc1\xcc\xd9&r2\xe4tQ0\x8aTN\xba\x1a\x19\xc9C\xd9>;E\xf4-\xbb\xe1\xcd\x9f\xdb\x7f\xaf\x077\x18\x95\x8b\x8c\x04\xa5\x03p/\x12\x97\x0c\xb5\x05\x1c\xd65\xce\xf7\x953\xe7\x00\x91x\x1b\x00\x90\xc0\xa6\t\xaf6\x15\x8ft\xc8\xa2_\xd9\x04\x98T\xf1\x7f\xd4\xbd\xb7\x80]\x0fI\xac\x82\xc5S\xb9\x02\x8c\x10]f\r\xfd9\xe4\xa2#X\xea\x04\xfei\xce\x86j\x15NE\xe4z\xd6\xf9\xdc\'\xf3%\x15\xe5V\x19\xe4$\xef*\xb4\xab\xc0=6Mt\x0fH\xee\xa2>\rT,\xe1`Q\xbe\xf7V\xf8\xe0\rXO\x00\x0c1<\xca\x06\x8d\xf4y\xa9-!\x02\xff\x89\x14A*N\xaaS\xd2\x88\x88v\xf6]t\xcf\tp;\xdd\t\x81%\xdd\xf4\xc8Y\xd6\xa9{\xce\'\xae\xc3\xb1\xbc\xae\x935N\x99\xd7\xb0H\xf9\x94\xdf\xcf\xf1g\xd9\x90-\x80\x8c\x84\xd7}]$\xb7 G-\xc2x\x83\xca^\x92U\xf4n\xf1\x96\x1f}1\xa2\x02\xb1U\xf1\xfd\xf0t\x91\x86 \x1a&[\x15\x88z^@\x13\x12m\x94\xa2v\xd9\xa1\x08k\xe5\xbe\x81o\x1a\xbdH\xa9\n\xf6R,3%Ez\x97\x97\t\x84p\xa1\xf97\xd7\xe2A\x8b\x84gE\xb3\xb9\x97\xce\x11y\xdd\xab\xa4\xe6\xf7\x88\xd3\xb0hg\x07\x10\xea]3I\x80#O\xf0\xbfW\xf75\xe5\xe9\x1c\xc6\x89Y\x01\xbcI\xbfB\x98\x0f\x1e\xb7\xc5', ttl=60)
INFO:twisted:Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x00000001062fb0c0>
INFO:twisted:Running command:  Counter(name='notification.throughput.bytes', count=2633)
INFO:twisted:Running command:  Counter(name='notification.sent', count=1)
INFO:twisted:Running command:  Wait(time=2)
INFO:twisted:Running command:  Counter(name='notification.throughput.bytes', count=2912)
INFO:twisted:Running command:  Counter(name='notification.sent', count=1)
INFO:twisted:Running command:  ExpectNotification(channel_id=u'e5b1225b-2c5f-41de-818e-155651b6d507', time=5)
INFO:twisted:Running command:  Counter(name='notification.sent', count=1)
INFO:twisted:Running command:  ExpectNotification(channel_id=u'022e5015-0994-49f5-8143-6e88876cce46', time=5)
INFO:twisted:Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x00000001076058c0>
INFO:twisted:Running command:  Disconnect()
INFO:twisted:Handling websocket data:  {'messageType': 'disconnect', 'was_clean': True, 'code': 1000, 'reason': None}
INFO:twisted:Stopping factory <autobahn.twisted.websocket.WebSocketClientFactory object at 0x000000010695e0c8>
INFO:twisted:Running command:  Disconnect()
INFO:twisted:Handling websocket data:  {'messageType': 'disconnect', 'was_clean': True, 'code': 1000, 'reason': None}
INFO:twisted:Stopping factory <autobahn.twisted.websocket.WebSocketClientFactory object at 0x0000000106532838>
INFO:twisted:Running command:  Counter(name='notification.sent', count=1)
INFO:twisted:Running command:  TimerEnd(name='update.latency')
Unhandled Error
Traceback (most recent call last):
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 142, in _run_command
    command_func(command)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 256, in timer_end
    self._send_command_result(duration)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 97, in _send_command_result
    self._run_safely(lambda: self._scenario[-1].send(result))
--- <exception caught here> ---
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 97, in <lambda>
    self._run_safely(lambda: self._scenario[-1].send(result))
  File "/Users/rpappalardo/git/ap-loadtester/aplt/scenarios.py", line 206, in notification_forever_unsubscribed
    yield ack(channel_id=notif["channelID"], version=notif["version"])
exceptions.TypeError: 'NoneType' object is not subscriptable

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 142, in _run_command
    command_func(command)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 256, in timer_end
    self._send_command_result(duration)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 97, in _send_command_result
    self._run_safely(lambda: self._scenario[-1].send(result))
--- <exception caught here> ---
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 97, in <lambda>
    self._run_safely(lambda: self._scenario[-1].send(result))
  File "/Users/rpappalardo/git/ap-loadtester/aplt/scenarios.py", line 206, in notification_forever_unsubscribed
    yield ack(channel_id=notif["channelID"], version=notif["version"])
exceptions.TypeError: 'NoneType' object is not subscriptable

INFO:twisted:Running command:  Counter(name='notification.received', count=1)
INFO:twisted:Running command:  TimerEnd(name='update.latency')
INFO:twisted:Got notif:  None
Unhandled Error
Traceback (most recent call last):
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 142, in _run_command
    command_func(command)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 256, in timer_end
    self._send_command_result(duration)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 97, in _send_command_result
    self._run_safely(lambda: self._scenario[-1].send(result))
--- <exception caught here> ---
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 97, in <lambda>
    self._run_safely(lambda: self._scenario[-1].send(result))
  File "/Users/rpappalardo/git/ap-loadtester/aplt/scenarios.py", line 38, in basic
    yield ack(channel_id=notif["channelID"], version=notif["version"])
exceptions.TypeError: 'NoneType' object is not subscriptable

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 142, in _run_command
    command_func(command)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 256, in timer_end
    self._send_command_result(duration)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 97, in _send_command_result
    self._run_safely(lambda: self._scenario[-1].send(result))
--- <exception caught here> ---
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 97, in <lambda>
    self._run_safely(lambda: self._scenario[-1].send(result))
  File "/Users/rpappalardo/git/ap-loadtester/aplt/scenarios.py", line 38, in basic
    yield ack(channel_id=notif["channelID"], version=notif["version"])
exceptions.TypeError: 'NoneType' object is not subscriptable

INFO:twisted:Handling websocket data:  {'messageType': 'disconnect', 'was_clean': False, 'code': 1006, 'reason': u'connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)'}
Unhandled Error
Traceback (most recent call last):
  File "/Users/rpappalardo/git/ap-loadtester/apenv/site-packages/autobahn-0.13.0-py2.7.egg/autobahn/twisted/websocket.py", line 172, in _onClose
    self.onClose(wasClean, code, reason)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 39, in onClose
    reason=reason))
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 307, in handle
    self._send_exception()
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 113, in _send_exception
    self._run_safely(throw)
--- <exception caught here> ---
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 112, in throw
    self._scenario[-1].throw(*sys.exc_info())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 305, in handle
    self._raise_unexpected_event(data)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 282, in _raise_unexpected_event
    self._last_command, data))
exceptions.Exception: Unexpected event. Last Command: timer_end; Data: {'messageType': 'disconnect', 'was_clean': False, 'code': 1006, 'reason': u'connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)'}

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/Users/rpappalardo/git/ap-loadtester/apenv/site-packages/autobahn-0.13.0-py2.7.egg/autobahn/twisted/websocket.py", line 172, in _onClose
    self.onClose(wasClean, code, reason)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 39, in onClose
    reason=reason))
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 307, in handle
    self._send_exception()
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 113, in _send_exception
    self._run_safely(throw)
--- <exception caught here> ---
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 112, in throw
    self._scenario[-1].throw(*sys.exc_info())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 305, in handle
    self._raise_unexpected_event(data)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 282, in _raise_unexpected_event
    self._last_command, data))
exceptions.Exception: Unexpected event. Last Command: timer_end; Data: {'messageType': 'disconnect', 'was_clean': False, 'code': 1006, 'reason': u'connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)'}

INFO:twisted:Stopping factory <autobahn.twisted.websocket.WebSocketClientFactory object at 0x0000000107b13c90>
INFO:twisted:Handling websocket data:  {'messageType': 'disconnect', 'was_clean': False, 'code': 1006, 'reason': u'connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)'}
Unhandled Error
Traceback (most recent call last):
  File "/Users/rpappalardo/git/ap-loadtester/apenv/site-packages/autobahn-0.13.0-py2.7.egg/autobahn/twisted/websocket.py", line 172, in _onClose
    self.onClose(wasClean, code, reason)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 39, in onClose
    reason=reason))
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 307, in handle
    self._send_exception()
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 113, in _send_exception
    self._run_safely(throw)
--- <exception caught here> ---
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 112, in throw
    self._scenario[-1].throw(*sys.exc_info())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 305, in handle
    self._raise_unexpected_event(data)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 282, in _raise_unexpected_event
    self._last_command, data))
exceptions.Exception: Unexpected event. Last Command: timer_end; Data: {'messageType': 'disconnect', 'was_clean': False, 'code': 1006, 'reason': u'connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)'}

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/Users/rpappalardo/git/ap-loadtester/apenv/site-packages/autobahn-0.13.0-py2.7.egg/autobahn/twisted/websocket.py", line 172, in _onClose
    self.onClose(wasClean, code, reason)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 39, in onClose
    reason=reason))
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 307, in handle
    self._send_exception()
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 113, in _send_exception
    self._run_safely(throw)
--- <exception caught here> ---
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 117, in _run_safely
    self._run_command(func())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 112, in throw
    self._scenario[-1].throw(*sys.exc_info())
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 305, in handle
    self._raise_unexpected_event(data)
  File "/Users/rpappalardo/git/ap-loadtester/aplt/client.py", line 282, in _raise_unexpected_event
    self._last_command, data))
exceptions.Exception: Unexpected event. Last Command: timer_end; Data: {'messageType': 'disconnect', 'was_clean': False, 'code': 1006, 'reason': u'connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)'}

INFO:twisted:Stopping factory <autobahn.twisted.websocket.WebSocketClientFactory object at 0x0000000107bf1b08>
INFO:twisted:Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x00000001062fb0c0>
INFO:twisted:Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x00000001062f84a0>
INFO:twisted:Main loop terminated.


~~~

**Comment by rpappalax** [comment]
looks like we may not be handling unclean disconnects properly

**Comment by rpappalax** [comment]
can't repro anymore so, closing
